---
# Iproute is required for quagga
- name: Install iproute
  apt:
    name: iproute
    state: present

- name: Download Quagga
  get_url:
    url: http://repo3.cumulusnetworks.com/repo/pool/cumulus/q/quagga/quagga_0.99.23.1-1+cl3u2_amd64.deb  # yamllint disable-line rule:line-length
    dest: /home/vagrant/quagga.deb

- name: Install Quagga
  apt:
    deb: /home/vagrant/quagga.deb
  register: install_quagga

- name: Copy Quagga daemons file
  copy:
    src: daemons
    dest: /etc/quagga/daemons
    backup: yes
  notify: restart quagga

- name: Enable Quagga Reload
  copy:
    src: quagga
    dest: /etc/default/quagga
  notify: restart quagga

- name: Check Apt hold for quagga
  command: apt-mark showhold quagga
  register: quagga_hold

- name: Set Apt hold on quagga package
  command: apt-mark hold quagga
  when: quagga_hold.stdout != "quagga"

- name: Force quagga changes
  meta: flush_handlers
